name: CI/CD Pipeline for Remix (with Vite)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Build Remix app
        run: |
          echo "Starting Remix build..."
          bun run build
          echo "Remix build completed."

      - name: Build Vite assets
        run: |
          echo "Starting Vite build..."
          bun run vite build
          echo "Vite build completed."


  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "${PRIVATE_KEY}" > private_key
          chmod 600 private_key
          ssh -i private_key -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
          echo "Starting deployment..."
          cd /opt/zephtech.com
          git pull origin main
          echo "Building on the server..."
          bun run build
          bun run vite build
          echo "Restarting server..."
          sudo systemctl restart zephtech.service
          echo "Deployment completed."
          EOF
          rm private_key
