name: CI/CD Pipeline for Remix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build Remix app
        run: bun run build

      - name: Run tests
        run: bun test
        continue-on-error: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Production
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "${PRIVATE_KEY}" > private_key
          chmod 600 private_key
          
          max_attempts=3
          attempt=1
          
          while [ $attempt -le $max_attempts ]; do
            echo "Deployment attempt $attempt of $max_attempts"
            
            if ssh -T -i private_key -o StrictHostKeyChecking=no -o ConnectTimeout=10 $SERVER_USER@$SERVER_IP << 'EOF'
              set -e
              cd /opt/zephtech.com
              git pull origin main
              bun install
              bun run build
              if ! sudo systemctl restart zephtech.service; then
                echo "Failed to restart service"
                exit 1
              fi
              exit 0
            EOF
            then
              echo "Deployment successful"
              rm private_key
              exit 0
            else
              echo "Deployment failed"
              if [ $attempt -eq $max_attempts ]; then
                echo "Max attempts reached. Deployment failed."
                rm private_key
                exit 1
              fi
              sleep 10
            fi
            
            attempt=$((attempt + 1))
          done